=== Omnia-Goher/ITI-OpenSourceApplicationDevelopment/XML/lab2/task2/employees.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT employees (employee)>
<!ELEMENT employee (name,email,phone)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== Omnia-Goher/ITI-OpenSourceApplicationDevelopment/XML/lab2/task2/employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "employees.dtd">
<employees>
    <employee>
        <name>Omnia</name>
        <email>omnia@gmail.com</email>
        <phone>01003911901</phone>
    </employee>
    <employee>
        <name>Eman</name>
        <email>eman44@gmail.com</email>
        <phone>0103255145</phone>
    </employee>
    <employee>
        <name>khaled</name>
        <email>khaled@gmail.com</email>
        <phone>01003911901</phone>
    </employee>
</employees>
